[env]
MISE_ENV_FILE = ".env"

[tools]
act = "latest"
actionlint = "latest"
age = "latest"
aqua = "latest"
bat = "latest"
bat-extras = "latest"
biome = "latest"
bottom = "latest"
btop = "latest"
ccache = "latest"
checkmake = "latest"
cosign = "latest"
delta = "latest"
difftastic = "latest"
direnv = "latest"
dive = "latest"
dua = "latest"
duf = "latest"
dust = "latest"
dyff = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gdu = "latest"
gh = "latest"
git-cliff = "latest"
gitleaks = "latest"
gitui = "latest"
glow = "latest"
go = "latest"
gup = "latest"
hadolint = "latest"
harper-cli = "latest"
harper-ls = "latest"
helm = "latest"
helm-docs = "latest"
java = "temurin-jre-21"
jless = "latest"
jnv = "latest"
jq = "latest"
k9s = "latest"
kind = "latest"
kubectl = "latest"
lazydocker = "latest"
lazygit = "latest"
lazyjournal = "latest"
lua-language-server = "latest"
lychee = "latest"
make = "latest"
marksman = "latest"
meson = "latest"
minikube = "latest"
ninja = "latest"
node = "latest"
pandoc = "latest"
perl = "latest"
pipx = "latest"
python = "latest"
ripgrep = "latest"
ripgrep-all = "latest"
ruff = "latest"
rust = { version = "latest", profile = "minimal" }
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
stylua = "latest"
taplo = "latest"
terraform = "latest"
tflint = "latest"
typst = "latest"
usage = "latest"
uv = "latest"
viddy = "latest"
yamlfmt = "latest"
yamllint = "latest"
yq = "latest"
zig = "latest"

"asdf:richin13/asdf-neovim" = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:cargo-cache" = "latest"
"cargo:cargo-update" = "latest"
"cargo:erdtree" = "latest"
"cargo:jinja-lsp" = "latest"
"cargo:mcat" = "latest"
"cargo:prosemd-lsp" = "latest"
"cargo:tex-fmt" = "latest"
"cargo:tlrc" = "latest"
"go:github.com/kubecolor/kubecolor" = "latest"
"go:github.com/marwanhawari/stew" = "latest"
"npm:@ansible/ansible-language-server" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:alex" = "latest"
"npm:awk-language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:bibtex-tidy" = "latest"
"npm:commitlint" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:doctoc" = "latest"
"npm:fixjson" = "latest"
"npm:gh-actions-language-server" = "latest"
"npm:jsonlint" = "latest"
"npm:markdown-toc" = "latest"
"npm:markdownlint-cli2" = "latest"
"npm:textlint" = "latest"
"npm:vim-language-server" = "latest"
"npm:write-good" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:ansible-dev-tools" = { version = "latest", uvx_args = "--with argcomplete" }
"pipx:ansible-lint" = "latest"
"pipx:argcomplete" = "latest"
"pipx:asciinema" = "latest"
"pipx:bandit" = "latest"
"pipx:clang-format" = "latest"
"pipx:cmakelint" = "latest"
"pipx:codespell" = "latest"
"pipx:cpplint" = "latest"
"pipx:curlylint" = "latest"
"pipx:darker" = "latest"
"pipx:docformatter" = "latest"
"pipx:fortls" = "latest"
"pipx:git-delete-merged-branches" = "latest"
"pipx:gitlint-core" = "latest"
"pipx:ipython" = "latest"
"pipx:jupytext" = "latest"
"pipx:mdformat" = "latest"
"pipx:mypy" = "latest"
"pipx:proselint" = "latest"
"pipx:ptpython" = "latest"
"pipx:pylama" = "latest"
"pipx:pylyzer" = "latest"
"pipx:pymarkdownlint" = "latest"
"pipx:pymarkdownlnt" = "latest"
"pipx:pytest" = "latest"
"pipx:sphinx-lint" = "latest"
"pipx:toml-sort" = "latest"
"pipx:trash-cli" = "latest"
"pipx:vulture" = "latest"
"pipx:yamlfix" = "latest"

[settings]
experimental = true
env_file = '.env'
idiomatic_version_file_enable_tools = ["ruby"]

# "cargo:carl" = "latest"
# "cargo:prosemd-lsp" = "latest"
# "cargo:ruplacer" = "latest"
# "cargo:tex-fmt" = "latest"
# "go:github.com/containers/podman-tui" = "latest"
# "pipx:ansible-core" = { version = "latest", pipx_args = "--include-deps", preinstall = "argcomplete" }
# "pipx:beautysh" = "latest" # errors out within vim with a module import error (same with pixi global install)
# ansible = "latest"
# btop = "latest"
# kubectl-convert = "latest"
# terraform-docs = "latest"
