# vim: ft=sh:foldmarker=(((,))):fdm=marker:foldlevel=0:tw=130:syntax=sh:expandtab:
# shellcheck shell=bash

# aliases for built-in & 3rd party tools (((
# Function to check if alias exists
alias_exists() {
  alias "$1" &>/dev/null
}

# Function to create an alias if the command exists
create_alias() {
  local command_name="$1"
  local alias_name="$2"
  local command_to_run="$3"

  if command_exists "$command_name"; then
    alias "$alias_name"="$command_to_run"
  else
    echo "Warning: '$command_name' not found. Skipping alias creation for '$alias_name'."
  fi
}

# Check for and create aliases for common tools

# rm alias based on available tools
if command_exists "gtrash"; then
  alias rm='gtrash put -RIfv'
elif command_exists "gomi"; then
  alias rm='gomi -v'
elif command_exists "trash-put"; then
  alias rm='trash-put -v'
elif command_exists "cnc" &>/dev/null && type "conceal"; then
  alias rm='cnc'
else
  alias rm='rm -Iv --preserve-root --one-file-system'
fi

# Git and Kubernetes aliases
if ! alias_exists "groot"; then
  create_alias "git rev-parse --show-toplevel" "groot" 'cd "$(git rev-parse --show-toplevel)"'
fi

if ! alias_exists "k"; then
  create_alias "kubectl" "k" "kubectl"
fi

# LS-related aliases
if command_exists "eza"; then
  alias ls='eza --icons=automatic -L 2'
  alias la='eza --icons=automatic -labghHmF --all'
  alias lg='eza --icons=automatic -labghHmF --group-directories-first'
  alias ll='eza --icons=automatic -labghHmF'
elif command_exists "lsd"; then
  alias ls='lsd -F'
  alias la='lsd -lAhF --group-dirs'
fi

# Other aliases for commands
create_alias "ansible" "ad" "ansible-doc"
create_alias "ansible" "al" "ansible-lint"
create_alias "ansible" "an" "ansible-navigator"
create_alias "ansible" "ap" "ansible-playbook"
create_alias "git" "gmake" "gmake -j \"\$(nproc)\""

# Compression aliases: `tarcbz2`, `tarcgz` with checks for `pv`
if command_exists "pv"; then
  create_alias "tarcbz2" 'tar --use-compress-program="lbzip2 | pv" -cf'
  create_alias "tarcgz" 'tar --use-compress-program="pigz --best --recursive | pv" -cf'
else
  create_alias "tarcbz2" 'tar --use-compress-program="lbzip2" -cf'
  create_alias "tarcgz" 'tar --use-compress-program="pigz --best --recursive" -cf'
fi

# Handle command-line tools like `ffmpeg` with standard flags
if command_exists "ffmpeg"; then
  alias ffmpeg='ffmpeg -hide_banner '
  alias ffplay='ffplay -hide_banner -autoexit '
  alias ffprobe='ffprobe -hide_banner '
fi

# Ping alias with prettier output if `prettyping` is installed
if command_exists "prettyping"; then
  alias ping='prettyping -c 5'
else
  alias ping='ping -c 5'
fi

# Alias for `top`/`htop` based on availability
if command_exists "btop"; then
  alias top='btop'
  alias htop='btop'
elif command_exists "btm"; then
  alias top='btm'
  alias htop='btm --basic'
  alias btmb='btm --basic'
fi

# Tar/Compression-related aliases
if command_exists "pixz"; then
  alias xz='pixz'
fi

if command_exists "unzrip"; then
  alias unzip='unzip'
fi

# Kubernetes (kubectl) alias with kubecolor if available
if command_exists "kubectl"; then
  if command_exists "kubecolor"; then
    alias kubectl='kubecolor --paging'
  fi
  alias k='kubectl'
fi

# Setup `watch` alias with better visualizations if `viddy` is present
if command_exists "viddy"; then
  alias watch='viddy --interval 30 --differences --skip-empty-diffs --disable_auto_save'
else
  alias watch='watch --interval 15 --color '
fi

# Check if tools like `bat` are available and use them
if command_exists "bat"; then
  helper() {
    "$@" --help 2>&1 | bat --plain --language=help
  }
  alias cat='bat'
  alias path='echo -e ${PATH//:/\\n} | bat'

  # man() function using `batman` (((
  if command_exists batman; then
    man() {
      BAT_THEME="Monokai Extended" batman "$@"
      return $?
    }
  fi
else
  alias path='echo -e ${PATH//:/\\n} | less'
fi

# Handle compressed files (.tar.bz2, .tar.gz, etc.)
if command_exists "lbzip2"; then
  alias bzip2='lbzip2'
  alias bunzip2='lbzip2 -d'
elif command_exists "pbzip2"; then
  alias bzip2='pbzip2'
  alias bunzip2='pbzip2 -d'
fi

if command_exists "pigz"; then
  alias gzip='pigz'
  alias gunzip='pigz -d'
  alias untar='tar --use-compress-program=pigz -xf'
fi

# Additional default alias for `ls` for sorting and output control
alias sl='ls -v'
alias ll='ls -lAhFv'
alias la='ls -lahv'
alias lt='ls -lAhFvrt' # sort by date
alias lx='ls -lAhFvBX' # sort by extension
alias lz='ls -lAhFvrS' # sort by size
alias l='ls -F'

# Final check for available tools for user aliases and utilities
if command_exists "termimage"; then
  alias termimage='termimage -s 51x14'
fi

# Make sure we don’t overwrite user's existing aliases
if ! alias_exists "topgrade"; then
  create_alias "topgrade" "pkgupdate" "topgrade --yes --cleanup"
fi

# Alias for `ps` with user-friendly output formatting
alias ps='ps uxf -j --cols $COLUMNS | less'

# Alias for easy directory navigation
alias d='dirs -p -v'
alias pd='pushd'
alias po='popd >/dev/null'

# Alias for `logoff` command
if command_exists "loginctl"; then
  alias logoff='(shopt -q login_shell && logout) || loginctl kill-user $(whoami)'
else
  alias logoff='(shopt -q login_shell && logout) || killall -u $(whoami)'
fi

# )))

# aliases for bash built-in & common/native *nix commands (from coreutils, util-linux etc) (((

# Safety features (((
# Ask, and then copy contents of directories (r)ecursively and explain (v) what was done
# alias cp='rsync -ae ssh'
alias cp='cp -Rivu'
alias cpa='rsync -vhae ssh --progress --append'
alias cpv='rsync -ah --info=progress2'
alias ln='ln -i'
alias mv='mv -iv'
alias rd='rmdir'

alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# )))

# cd aliases (((
alias cd..='\cd ..'
alias ..='\cd ..'             # Go up one directory'
alias ...='\cd ../..'         # Go up two directories'
alias ....='\cd ../../..'     # Go up three directories'
alias .....='\cd ../../../..' # Go up four directories'
# )))

# test -x "$HOME/bin/less" && alias less='"$HOME/bin/less"'

# alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"' # Add an "alert" alias for long running commands.  Use like so: sleep 10; alert
alias free='free -h -m -l -t'
alias grep='grep -Ei --color=auto'
alias h='history 21'
alias info='info --init-file "$HOME/.config/info/infokey"'
alias ip='ip -brief -color=auto'
alias md='mkdir -p -v'
alias mkdir='mkdir -p -v'
alias more=less
alias mysudo='sudo env "PATH=$PATH" ' # https://unix.stackexchange.com/questions/83191/how-to-make-sudo-preserve-path
alias nano='nano --nowrap --softwrap'
alias open='xdg-open'
alias reboot='echo -e "\n Hostname: $(hostname)\n Warning! You are rebooting $(hostname).\n This may be a remote machine.\n Use backslash(\) reboot to proceed...\n\n"'
# alias sshhosts="grep -w -i -E 'Host|HostName' ~/.ssh/config | sed 's/Host //' | sed 's/HostName //'" # https://dev.to/ahmedmusallam/how-to-autocomplete-ssh-hosts-1hob
alias wget='wget -c --hsts-file="$HOME/.cache/wget-hsts"'
alias which='which -a'

# Windows-like aliases (((
alias cmd="bash"
alias chdir="pwd"
alias del='rm'
alias delete="rm"
alias dir="ls"
alias tracert="traceroute"
# )))



# )))
