# vim: ft=sh:foldmarker=(((,))):fdm=marker:foldlevel=0:tw=130:syntax=sh:expandtab:
# shellcheck shell=bash

# aliases for built-in & 3rd party tools (((

# ansible aliases (((
if [ -x "$(command -v ansible)" ]; then
  alias ad='ansible-doc'
  alias al='ansible-lint'
  alias an='ansible-navigator'
  alias ap='ansible-playbook'
  # alias acl='ansible-config list'
  # alias aig='ansible-inventory --graph'
  # alias aigv='ansible-inventory --graph --vars'
  # alias ail='ansible-inventory --list -y'
  # alias av='ansible-vault'
  if [ -x "$(command -v register-python-argcomplete)" ]; then
    eval "$(register-python-argcomplete ansible)"
    eval "$(register-python-argcomplete ansible-config)"
    eval "$(register-python-argcomplete ansible-console)"
    eval "$(register-python-argcomplete ansible-doc)"
    eval "$(register-python-argcomplete ansible-galaxy)"
    eval "$(register-python-argcomplete ansible-inventory)"
    eval "$(register-python-argcomplete ansible-lint)"
    eval "$(register-python-argcomplete ansible-navigator)"
    eval "$(register-python-argcomplete ansible-playbook)"
    eval "$(register-python-argcomplete ansible-pull)"
    eval "$(register-python-argcomplete ansible-test)"
    eval "$(register-python-argcomplete ansible-vault)"
    complete -F _complete_alias ad 2>/dev/null
    complete -F _complete_alias al 2>/dev/null
    complete -F _complete_alias an 2>/dev/null
    complete -F _complete_alias ap 2>/dev/null
  fi
fi
# )))

# apt alias (((
if [ -x "$(command -v nala)" ]; then
  alias apt='nala'
fi
# )))

# custom aliases and functions using bat (((
test -x "$(command -v bat)" && BAT_PRESENT=1
if [ "$BAT_PRESENT" != "" ]; then
  # alias bathelp='bat --plain --language=help'
  helper() {
    "$@" --help 2>&1 | bat --plain --language=help
  }
  alias cat='bat'
  alias path='echo -e ${PATH//:/\\n} | bat' # Print each PATH entry on a separate line
  # alias dmesg='dmesg -HL --color=always | bat'

  # man() function using `batman` (((
  if [ -x "$(command -v batman)" ]; then
    man() {
      BAT_THEME="Monokai Extended" batman "$@"
      return $?
    }
  fi
  # )))
else
  alias path='echo -e ${PATH//:/\\n} | less' # Print each PATH entry on a separate line
  # alias dmesg='dmesg -HL --color=always | less'
fi
# )))

# bc alias (((
if [ -x "$(command -v numbat)" ]; then
  alias bc='numbat'
elif [ -x "$(command -v fend)" ]; then
  alias bc='fend'
elif [ -x "$(command -v calc)" ]; then
  alias bc='calc'
elif [ -x "$(command -v kalc)" ]; then
  alias bc='kalc'
else
  alias bc='bc -l'
fi
# )))

# cal aliases (((
if [ -x "$(command -v carl)" ]; then
  alias cal='carl'
elif [ -x "$(command -v ncal)" ]; then
  alias ncal='ncal -b -3 -w' # oldstyle format for ncal output
  alias cal='ncal'
fi
# )))

# dirs/pushd aliases (((
alias d='dirs -p -v'
alias p='pushd'
alias popd='popd >/dev/null'
# )))

# df alias (((
if [ -x "$(command -v dysk)" ]; then
  alias df="dysk -s free-d -c label+default+dev"
else
  alias df='df -x"squashfs" -x"cgroup" -x"tmpfs" -Th --total'
fi
# )))

# diff aliases (((
if [ -x "$(command -v difft)" ]; then
  alias diff='difft'
elif [ -x "$(command -v batdiff)" ]; then
  alias diff='batdiff'
elif [ -x "$(command -v delta)" ]; then
  alias diff='delta'
elif [ -x "$(command -v colordiff)" ]; then
  alias diff='colordiff -u'
else
  alias diff='diff -u --minimal --color=auto'
fi
# )))

# ffmpeg aliases (((
if [ -x "$(command -v ffmpeg)" ]; then
  alias ffmpeg='ffmpeg -hide_banner '
  alias ffplay='ffplay -hide_banner -autoexit '
  alias ffprobe='ffprobe -hide_banner '
fi
# )))

test -x "$(command -v git)" && alias groot='cd $(git rev-parse --show-toplevel)'

test -x "$(command -v gmake)" && alias gmake='gmake -j "$(nproc)"'

test -x "$(command -v goawk)" && alias awk='goawk'

# ipyc alias (((
if [ -x "$(command -v euporie)" ]; then
  alias ipyc='euporie console'
  alias ipyn='euporie notebook'
elif [ -x "$(command -v bpython)" ]; then
  alias ipyc='bpython'
elif [ -x "$(command -v ptipython)" ]; then
  alias ipyc='ptipython'
fi
# )))

# kubernetes alias (((
if [ -x "$(command -v kubectl)" ]; then
  if [ -x "$(command -v kubecolor)" ]; then
    alias kubectl='kubecolor --paging'
  fi
  alias k='kubectl'
  # complete -F __start_kubectl k # https://stackoverflow.com/a/56227981
  complete -o default -F __start_kubectl k # https://kubernetes.io/docs/reference/kubectl/quick-reference/#bash
fi
# )))

# logoff alias (((
if [ -x "$(command -v loginctl)" ]; then
  alias logoff='(shopt -q login_shell && logout) || loginctl kill-user $(whoami)'
elif [ -x "$(command -v killall)" ]; then
  alias logoff='(shopt -q login_shell && logout) || killall -u $(whoami)'
fi
# )))

# ls aliases in linux (((
# if xhost >&/dev/null && [[ "$(command -v eza)" ]]; then
if [[ "$(command -v eza)" ]]; then
  alias ls='eza --icons=automatic -L 2'
  alias la='eza --icons=automatic -labghHmF --all'
  alias lg='eza --icons=automatic -labghHmF --group-directories-first'
  alias ll='eza --icons=automatic -labghHmF'
  alias lt='eza --icons=automatic -labghHF --sort newest' # sort by date
  # alias lsf='eza --icons=automatic -f'                  # https://stackoverflow.com/a/70698721
  # alias lsfa='lsf --icons=automatic --all'
else
  # if xhost >&/dev/null && [[ "$(command -v lsd)" ]]; then
  if [[ "$(command -v lsd)" ]]; then
    alias ls='lsd -F'
    alias lg='ls -lAhFv --group-dirs'
  else
    alias ls='ls -hF --color=auto'
    alias lg='ls -lAhFv --group-directories-first'
  fi

  alias sl='ls -v'
  alias ll='ls -lAhFv'
  alias la='ls -lahv'
  # alias lt='ls -lAhFvrt | less' # sort by date
  alias lt='ls -lAhFvrt' # sort by date
  alias lx='ls -lAhFvBX' # sort by extension
  alias lz='ls -lAhFvrS' # sort by size
  # alias l='ls -CF'
  alias l='ls -F'
  # alias lr='ls -R'       # recursive ls
fi
# )))

# make alias (((
if [ -x "$(command -v colormake)" ]; then
  alias make='colormake -j "$(nproc)"'
elif [ -x "$(command -v make)" ]; then
  alias make='make -j "$(nproc)"'
fi
# )))

# ping alias (((
if [ -x "$(command -v prettyping)" ]; then
  alias ping='prettyping -c 5'
else
  alias ping='ping -c 5'
fi
# )))

# ps alias (((
# if [ -x "$(command -v procs)" ]; then
#   alias ps='procs --tree'
# else
alias ps='ps uxf -j --cols $COLUMNS | less' # linux alias for ps
# fi
# )))

# rm alias (((
if [ -x "$(command -v gtrash)" ]; then
  alias rm='gtrash put -RIfv'
  alias trash-empty='gtrash find --rm'
elif [ -x "$(command -v gomi)" ]; then
  alias rm='gomi -v'
elif [ -x "$(command -v trash-put)" ]; then
  alias rm='trash-put -v'
elif [ -x "$(command -v cnc)" ] && [ -x "$(command -v conceal)" ]; then
  alias rm='cnc'
elif [ -x "$(command -v timeout)" ]; then
  # safer alternative w/ timeout, not stored in history. 'rm -i' prompts for every file
  alias rm=' timeout 3 rm -Iv --preserve-root --one-file-system'
else
  alias rm='rm -Iv --preserve-root --one-file-system'
fi
# )))

# test -x "$(command -v spack)" && alias spackupgrade='cd $SPACK_ROOT && git stash && git pull && git stash apply && spack mark -i -a && spack concretize --fresh --force && spack install && spack gc -y && cd -'

test -x "$(command -v termimage)" && alias termimage='termimage -s 51x14'

# top aliases (((
if [ -x "$(command -v btop)" ]; then
  alias top='btop'
  alias htop='btop'
elif [ -x "$(command -v btm)" ]; then
  alias top='btm'
  alias htop='btm --basic'
  alias btmb='btm --basic'
fi
# )))

if [ -x "$(command -v terraform)" ]; then
  alias tf='terraform'
  alias tfa='terraform apply'
  alias tfaa='terraform apply -auto-approve'
  alias tfdd='terraform destroy -auto-approve'
  alias tff='terraform fmt'
  alias tfi='terraform init'
  alias tfiu='terraform init -upgrade'
  alias tfo='terraform output'
  alias tfv='terraform validate'
fi

if [ -x "$(command -v topgrade)" ]; then
  alias pkgupdate='topgrade --yes --cleanup'
fi

test -x "$(command -v mtr)" && alias traceroute='mtr'

# tree aliases (((
if [ -x "$(command -v erd)" ]; then
  alias tree='erd --level 2 --icons --suppress-size --pattern ".*" --layout inverted --sort name'
  alias tree3='tree --level 3 --pattern ".*"'

  alias stree='erd -H --level 2 --icons --pattern ".*" --layout inverted'
  alias stree3='stree --level 3'

  alias treel='erd -H --level 2 --icons --suppress-size --layout inverted --sort name'
  alias treel3='treel --level 3'

  alias streel='erd -H --level 2 --icons --layout inverted'
  alias streel3='streel --level 3'
elif [ -x "$(command -v tree)" ]; then
  alias tree='tree -a -C -I .git -I .vendor -L 2'
  alias ttree='tree --noreport'
fi
# )))

# watch alias (((
if [ -x "$(command -v viddy)" ]; then
  alias watch='viddy --interval 30 --differences --skip-empty-diffs --disable_auto_save '
else
  alias watch='watch --interval 15 --color ' # https://unix.stackexchange.com/questions/25327/watch-command-alias-expansion https://unix.stackexchange.com/questions/453858/watch-command-alias-expansion-and-need-to-use-quotes A trailing space in VALUE causes the next word to be checked for alias substitution when the alias is expanded.
fi
# )))

# vim/neovim aliases (((
if [ -x "$(command -v nvim)" ]; then
  if [ "$EDITOR" != "" ]; then
    if ! [ -d "$HOME/.local/state/astronvim" ]; then
      alias nvim="nvim --headless -c 'quitall' && \nvim"
    else
      alias nvim="$EDITOR"
    fi
    alias vimdiff='nvim -d'
    alias oldvim="\vim"
    alias vim="nvim"
    alias vi="nvim"
    alias view="nvim -R"
    # astronvim alias(((
    # if [ -d "$HOME"/.config/astronvim_template ]; then
    #   alias astronvim="NVIM_APPNAME=astronvim_template nvim"
    # fi
    # )))
  fi
  # fi
elif [ -x "$(command -v vim)" ]; then
  # alias vim='vim --servername VIM'
  alias vi="vim"
fi
# )))

# aliases for compression tools (((

# Cross-platform compression file-formats (((
# Updated on 10 Feb 2024
# 7z: default lzma2. (7z decompression is single threaded). It does multithread compression (by default even). The 7z format does not store filesystem permissions (such as UNIX owner/group permissions or NTFS ACLs), and hence can be inappropriate for backup/archival purposes
# dar: disk archive (also the name of the tool is dar). Is GPL
# packARC: Good for media files. https://github.com/packjpg/packARC
# zip: introduced: 1989. latest update: 2016
# zpaq: introduced: 2009. latest update: 2016
# )))

# Notes on multi-core compresson tools (((

# lbzip2: *nix only. Parallel bzip2 compression utility, suited for serial and parallel processing
# lrzip: Compression utility that excels at compressing large files
# pbzip2: Parallel implementation of the bzip2 block-sorting file compressor
# pigz: Parallel implementation of gzip. It's a fully functional replacement for gzip
# pixz: Parallel indexing XZ compression, fully compatible with XZ. LZMA and LZMA2
# plzip: Has windows port. Massively parallel (multi-threaded) lossless data compressor based on lzlib
# PXZ: Runs LZMA compression on multiple cores and processors

# migz (lz format) tarlz (lz format), pixz (xz format), pzstd (zstd format) and lbzip2 (bz2 format) are the best since they support parallel decompression

# smallest filesize: pxz and pixz are faster; plzip and lrzip are slower
# largest filesize: pigz

# for algorithms, zpaq produces the smallest archives, but is the slowest
# )))

# aliases for bzip2 format (((
if [ -x "$(command -v lbzip2)" ]; then # supports parallel decompression
  alias bzip2='lbzip2'
  alias bunzip2='lbzip2 -d'
  if [ -x "$(command -v pv)" ]; then
    alias tarcbz2='tar --use-compress-program="lbzip2 | pv" -cf'
  else
    alias tarcbz2='tar --use-compress-program="lbzip2" -cf'
  fi
elif [ -x "$(command -v pbzip2)" ]; then
  alias bzip2='pbzip2'
  alias bunzip2='pbzip2 -d'
  if [ -x "$(command -v pv)" ]; then
    alias tarcbz2='tar --use-compress-program="pbzip2 | pv" -cf'
  else
    alias tarcbz2='tar --use-compress-program="pbzip2" -cf'
  fi
fi
# )))

# aliases for .gz format (((
# Can use 'pigz' to compress in 'zip' format by using the -K (upper case) flag e.g.: pigz -k -K archlinux.iso
if [ -x "$(command -v pigz)" ]; then
  alias gzip='pigz'
  alias gunzip='pigz -d'
  if [ -x "$(command -v pv)" ]; then
    alias tarcgz='tar --use-compress-program="pigz --best --recursive | pv" -cf'
  else
    alias tarcgz='tar --use-compress-program="pigz --best --recursive" -cf'
  fi
  # export TAR_OPTIONS="--use-compress-program=pbzip2" # https://askubuntu.com/questions/62607/whats-the-best-way-to-use-parallel-bzip2-and-gzip-by-default
  alias untar='tar --use-compress-program=pigz -xf'
fi
# )))

test -x "$(command -v pixz)" && alias xz='pixz' # alias for .xz format

test -x "$(command -v unzrip)" && alias unzip='unzip' # alias for unzip
# )))

# aliases for batgrep/ripgrep (((
if [ -x "$(command -v rg)" ]; then
  if [ -x "$(command -v batgrep)" ]; then
    alias rg='batgrep'
    alias hisgrep='history|batgrep'
  else
    alias hisgrep='history|rg'
  fi
  alias rg='rg --engine=auto'
  alias rgi='rg -p'
  # if [ -x "$(command -v delta)" ]; then
  #     rgp() {
  #         if [ -t 1 ]; then
  #             command rg --engine=auto --json "$@" | delta
  #         else
  #             command rg --engine=auto "$@"
  #         fi
  #     }
  # fi
else
  alias hisgrep='history|grep'
fi
# )))

# )))

# aliases for bash built-in & common/native *nix commands (from coreutils, util-linux etc) (((

# Safety features (((
# Ask, and then copy contents of directories (r)ecursively and explain (v) what was done
# alias cp='rsync -ae ssh'
alias cp='cp -Rivu'
alias cpa='rsync -vhae ssh --progress --append'
alias cpv='rsync -ah --info=progress2'
alias ln='ln -i'
alias mv='mv -iv'
alias rd='rmdir'

alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# )))

# cd aliases (((
alias cd..='\cd ..'
alias ..='\cd ..'             # Go up one directory'
alias ...='\cd ../..'         # Go up two directories'
alias ....='\cd ../../..'     # Go up three directories'
alias .....='\cd ../../../..' # Go up four directories'
# )))

# test -x "$HOME/bin/less" && alias less='"$HOME/bin/less"'

# alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"' # Add an "alert" alias for long running commands.  Use like so: sleep 10; alert
alias free='free -h -m -l -t'
alias grep='grep -Ei --color=auto'
alias h='history 21'
alias info='info --init-file "$HOME/.config/info/infokey"'
alias ip='ip -brief -color=auto'
alias md='mkdir -p -v'
alias mkdir='mkdir -p -v'
alias more=less
alias mysudo='sudo env "PATH=$PATH" ' # https://unix.stackexchange.com/questions/83191/how-to-make-sudo-preserve-path
alias nano='nano --nowrap --softwrap'
alias open='xdg-open'
alias reboot='echo -e "\n Hostname: $(hostname)\n Warning! You are rebooting $(hostname).\n This may be a remote machine.\n Use backslash(\) reboot to proceed...\n\n"'
# alias sshhosts="grep -w -i -E 'Host|HostName' ~/.ssh/config | sed 's/Host //' | sed 's/HostName //'" # https://dev.to/ahmedmusallam/how-to-autocomplete-ssh-hosts-1hob
alias wget='wget -c --hsts-file="$HOME/.cache/wget-hsts"'
alias which='which -a'

# Windows-like aliases (((
alias cmd="bash"
alias chdir="pwd"
alias del='rm'
alias delete="rm"
alias dir="ls"
alias tracert="traceroute"
# )))

# )))

# # fd aliases (((
# if [ -x "$(command -v fd)" ]; then
#   alias fdc='fd --color always'
# fi
# # )))
# alias gitbr='git rev-parse --abbrev-ref HEAD' # https://stackoverflow.com/questions/6245570/how-to-get-the-current-branch-name-in-git
